core/urls.py
from django import views
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include
from core.views import generate_report, add_to_cart, add_to_wishlist, ajax_add_review, ajax_contact_form, cart_view, \
    category_list_view, category_product_list__view, checkout_view, customer_dashboard, delete_item_from_cart, \
    filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, \
    product_detail_view, product_list_view, remove_wishlist, search_view, sign_in, tag_list, update_cart, \
    vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, privacy_policy, terms_of_service, sign_in, \
    sign_up, change_password, search_characters

app_name = "core"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),

    # Category
    path("category/", category_list_view, name="category-list"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list__view, name="category-product-list"),

    # Vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),

    # Tags
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add Review
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", search_view, name="search"),
    path('search_characters/', search_characters, name='search_characters'),

    # Filter product URL
    path("filter-products/", filter_product, name="filter-product"),

    # Add to cart URL
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    # Cart Page URL
    path("cart/", cart_view, name="cart"),

    # Delete ITem from Cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update  Cart
    path("update-cart/", update_cart, name="update-cart"),

    # Checkout  URL
    path("checkout/", checkout_view, name="checkout"),

    # Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),

    # Payment Successful
    path("payment-completed/", payment_completed_view, name="payment-completed"),

    # Payment Failed
    path("payment-failed/", payment_failed_view, name="payment-failed"),

    # Dahboard URL
    path("dashboard/", customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    # Making address default
    path("make-default-address/", make_address_default, name="make-default-address"),

    # wishlist page
    path("wishlist/", wishlist_view, name="wishlist"),

    # adding to wishlist
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    # Remvoing from wishlist
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),

    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),

    path("about_us/", about_us, name="about_us"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),

    

    # Redirecting to sign-in page
    path("sign-in/", sign_in, name="sign_in"),

    # Redirecting to sign-up page
    path("sign-up/", sign_up, name="sign_up"),

    path('generate-report/', generate_report, name='generate_report'),

    # Change password
    path('change-password/', change_password, name='change-password'),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    # Serve media files through Django in production (not recommended for high-traffic sites)
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

core/forms.py
from django import forms
from stripe import Review 
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Write review"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']


from userauths.models import ContactUs
class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['full_name', 'email', 'phone', 'subject', 'message']

core/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.hashers import make_password
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from taggit.models import Tag
from core.models import Product, Vendor, CartOrderProducts, ProductReview, wishlist_model, Address
from userauths.models import ContactUs, Profile
from core.forms import ProductReviewForm
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .forms import ContactForm
import calendar
from django.db.models import Count, Avg, Q, Sum
from django.db.models.functions import ExtractMonth
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    products = Product.objects.filter(product_status="published", featured=True).order_by("-id")

    # Fetch the wishlist items of the currently logged-in user if authenticated
    wishlist_items = []
    if request.user.is_authenticated:
        wishlist_items = wishlist_model.objects.filter(user=request.user).values_list('product_id', flat=True)

    # Fetch cart data from session or create an empty dictionary if it doesn't exist
    cart_data_obj = request.session.get('cart_data_obj', {})

    # Iterate through products and check if each product is in the cart
    for product in products:  # Use a different variable name here
        product.in_cart = str(product.id) in cart_data_obj

    # Fetch the top selling products based on the sum of quantities sold
    top_selling_products = Product.objects.annotate(total_qty_sold=Sum('cartorderproducts__qty')).order_by(
        '-total_qty_sold')[:3]

    # Fetch the trending products
    trending_products = Product.objects.filter(product_status="published").order_by('-date')[:3]

    # Fetching recently added products
    recently_added_products = Product.objects.filter(product_status="published").order_by("-date")[:3]

    # Fetch the top-rated products
    top_rated_products = Product.objects.filter(product_status="published").annotate(average_rating=Avg('reviews__rating')).order_by('-average_rating')[:3]

    # Calculate average rating for each product
    for product in top_selling_products:
        product.total_qty_sold = product.cartorderproducts_set.aggregate(Sum('qty'))['qty__sum']
        avg_rating = product.reviews.aggregate(Avg('rating'))['rating__avg'] or 0
        adjusted_rating = avg_rating * 20
        product.average_rating = adjusted_rating
        product.display_rating = avg_rating

    for product in trending_products:
        avg_rating = product.reviews.aggregate(Avg('rating'))['rating__avg'] or 0
        adjusted_rating = avg_rating * 20
        product.average_rating = adjusted_rating
        product.display_rating = avg_rating

    for product in recently_added_products:
        avg_rating = product.reviews.aggregate(Avg('rating'))['rating__avg'] or 0
        adjusted_rating = avg_rating * 20
        product.average_rating = adjusted_rating
        product.display_rating = avg_rating

    for product in top_rated_products:
        avg_rating = product.reviews.aggregate(Avg('rating'))['rating__avg'] or 0
        adjusted_rating = avg_rating * 20
        product.average_rating = adjusted_rating
        product.display_rating = avg_rating

    context = {
        'products': products,
        'top_selling_products': top_selling_products,
        'recently_added_products': recently_added_products,
        'top_rated_products': top_rated_products,
        'trending_products': trending_products,
        'wishlist_items': wishlist_items
    }

    return render(request, 'core/index.html', context)


def product_list_view(request):
    products = Product.objects.filter(product_status="published").order_by("-id")
    tags = Tag.objects.all().order_by("-id")[:6]

    # Fetch cart data from session or create an empty dictionary if it doesn't exist
    cart_data_obj = request.session.get('cart_data_obj', {})

    # Iterate through products and check if each product is in the cart
    for product in products:  # Use a different variable name here
        product.in_cart = str(product.id) in cart_data_obj

    # Fetch the wishlist items of the currently logged-in user if authenticated
    wishlist_items = []
    if request.user.is_authenticated:
        wishlist_items = wishlist_model.objects.filter(user=request.user).values_list('product_id', flat=True)

    context = {
        'products': products,
        'tags': tags,
        'wishlist_items': wishlist_items
    }

    return render(request, 'core/product-list.html', context)


def category_list_view(request):
    categories = Category.objects.all()

    context = {
        "categories":categories
    }
    return render(request, 'core/category-list.html', context)


def category_product_list__view(request, cid):
    category = Category.objects.get(cid=cid) # food, Cosmetics
    products = Product.objects.filter(product_status="published", category=category)

    # Fetch cart data from session or create an empty dictionary if it doesn't exist
    cart_data_obj = request.session.get('cart_data_obj', {})

    # Iterate through products and check if each product is in the cart
    for product in products:  # Use a different variable name here
        product.in_cart = str(product.id) in cart_data_obj

    # Fetch the wishlist items of the currently logged-in user if authenticated
    wishlist_items = []
    if request.user.is_authenticated:
        wishlist_items = wishlist_model.objects.filter(user=request.user).values_list('product_id', flat=True)

    context = {
        'category': category,
        'products': products,
        'wishlist_items': wishlist_items
    }
    return render(request, "core/category-product-list.html", context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors": vendors,
    }
    return render(request, "core/vendor-list.html", context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(vendor=vendor, product_status="published").order_by("-id")

    # Fetch cart data from session or create an empty dictionary if it doesn't exist
    cart_data_obj = request.session.get('cart_data_obj', {})

    # Iterate through products and check if each product is in the cart
    for product in products:  # Use a different variable name here
        product.in_cart = str(product.id) in cart_data_obj

    # Fetch the wishlist items of the currently logged-in user if authenticated
    wishlist_items = []
    if request.user.is_authenticated:
        wishlist_items = wishlist_model.objects.filter(user=request.user).values_list('product_id', flat=True)

    context = {
        'vendor': vendor,
        'products': products,
        'wishlist_items': wishlist_items
    }
    return render(request, "core/vendor-detail.html", context)


def product_detail_view(request, pid):
    product = Product.objects.get(pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)

    # Check if the product is in the wishlist
    is_in_wishlist = False
    if request.user.is_authenticated:
        is_in_wishlist = wishlist_model.objects.filter(product=product, user=request.user).exists()

    # Getting all reviews related to a product
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    # Getting average review
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    # Product Review form
    review_form = ProductReviewForm()

    make_review = True 

    if request.user.is_authenticated:
        try:
            address = Address.objects.get(status=True, user=request.user)
            user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
            if user_review_count > 0:
                make_review = False
        except ObjectDoesNotExist:
            address = None
            make_review = False
            messages.warning(request, "No active address found. Please add an address.")

    else:
        address = "Login To Continue"

    p_image = product.p_images.all()

    # Fetch cart data from session or create an empty dictionary if it doesn't exist
    cart_data_obj = request.session.get('cart_data_obj', {})

    # Iterate through products and check if each product is in the cart
    product.in_cart = str(product.id) in cart_data_obj

    # Fetch cart data from session or create an empty dictionary if it doesn't exist
    cart_data_obj = request.session.get('cart_data_obj', {})

    # Iterate through products and check if each product is in the cart
    for prod in products:  # Use a different variable name here
        prod.in_cart = str(prod.id) in cart_data_obj

    # Fetch the wishlist items of the currently logged-in user if authenticated
    wishlist_items = []
    if request.user.is_authenticated:
        wishlist_items = wishlist_model.objects.filter(user=request.user).values_list('product_id', flat=True)

    context = {
        "p": product,
        "address": address,
        "make_review": make_review,
        "review_form": review_form,
        "p_image": p_image,
        "average_rating": average_rating,
        "reviews": reviews,
        "products": products,
        "wishlist_items": wishlist_items,
        "is_in_wishlist": is_in_wishlist
    }

    return render(request, "core/product-detail.html", context)


def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")

    tag = None 
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)

templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col" class="text-center">Quantity</th>
                                    <th scope="col">Subtotal</th>
<!--                                    <th scope="col" class="">Refresh</th>-->
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-detail' item.pid %}">{{ item.title }}</a></h6>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 id="price-{{ product_id }}" class="text-body">TJS{{ item.price|floatformat:2 }}</h4>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <div class="mr-15">
                                            <input type="number" min="1" placeholder="Qty" class="w-25 product-qty-{{ product_id }} product-qty" data-product="{{ product_id }}" name="" value="{{ item.qty }}" id="qty-{{ product_id }}">
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 id="subtotal-{{ product_id }}" class="text-brand subtotal">TJS{% widthratio item.price 1 item.qty %}</h4>
                                    </td>
                                    <!-- <td class="action text-center" data-title="Refresh"><a href="#" class="text-body"><i class="fi-rs-refresh"></i></a></td> -->
<!--                                    <td class="action text-center" data-title="Remove"><button style="border: none; background: none;"  class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></button></td>-->
                                    <td class="action text-center" data-title="Remove"><button style="border: none; background: none;"  class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></button></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 id="cart-subtotal" class="text-brand text-end">TJS{{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">Free</h5>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 id="cart-total" class="text-brand text-end">TJS{{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {% if totalcartitems %}
                        <a href="{% url 'core:checkout' %}" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></a>
                        {% endif %}                    </div>
                </div>
            </div>
        </div>
    </main>
<script>
    $(document).ready(function() {
        // Function to update subtotal when quantity changes
        function updateSubtotal(productId) {
            var quantity = parseInt($("#qty-" + productId).val());
            var price = parseFloat($("#price-" + productId).text().replace("TJS", ""));
            var subtotal = quantity * price;
            $("#subtotal-" + productId).text("TJS" + subtotal.toFixed(2));
            $("#subtotal-" + productId).text();
            // Update cart subtotal
            var cartSubtotal = 0;
            $(".subtotal").each(function() {
                var subtotalValue = parseFloat($(this).text().replace("TJS", "").replace(",", ""));
                cartSubtotal += subtotalValue;
            });
            $("#cart-subtotal").text("TJS" + cartSubtotal.toFixed(2));

            // Update total
            var shipping = 0; // Free shipping for now
            var total = cartSubtotal + shipping;
            $("#cart-total").text("TJS" + total.toFixed(2));

            // Send AJAX request to update session data
            $.ajax({
                type: "GET",
                url: "{% url 'core:update-cart' %}",
                data: {
                    'id': productId,
                    'qty': quantity,
                },
                success: function(response) {
                    // Update cart list asynchronously
                    $("#cart-list").html(response.data);
                    $("#totalcartitems").text(response.totalcartitems);
                },
                error: function(xhr, status, error) {
                    console.error(xhr.responseText);  // Log any errors
                }
            });
        }

        // Event listener for quantity change
        $(".product-qty").on("change", function() {
            var productId = $(this).data("product");
            updateSubtotal(productId);
        });
    });
</script>

{% endblock content %}

templates/core/vendor-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <!--End header-->
    <main class="main pages mb-80">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}"     rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Vendors List
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="archive-header-2 text-center">
                    <h1 class="display-2 mb-50">Vendors List</h1>
                </div>
                <div class="row vendor-grid">
                    {% for v in vendors %}
                    <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                        <div class="vendor-wrap style-2 mb-40">
                            <div class="product-badges product-badges-position product-badges-mrg">
                                <!-- <span class="hot">Mall</span> -->
                            </div>
                            <div class="vendor-img-action-wrap">
                                <div class="vendor-img">
                                    <a href="{% url 'core:vendor-detail' v.vid %}">
                                        <img class="default-img" src="{{v.image.url}}" alt="" />
                                    </a>
                                </div>
                                <div class="mt-10">
                                    <span class="font-small total-product">{{v.product.all.count}} Products</span>
                                </div>
                            </div>
                            <div class="vendor-content-wrap">
                                <div class="mb-30">
                                    <div class="product-category">
                                        <span class="text-muted">Since {{v.date|date:"Y"}}</span>
                                    </div>
                                    <h4 class="mb-5"><a href="{% url 'core:vendor-detail' v.vid %}">{{v.title}}</a></h4>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                        <ul class="contact-infor text-muted">
                                            <li><img src="assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span>{{v.address}}</span></li>
                                            <li><img src="assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span>{{v.contact}}</span></li>
                                        </ul>
                                        <br>
                                    </div>
                                    <br>
                                    <a href="{% url 'core:vendor-detail' v.vid %}" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>

    {% endblock content %}